version: '3'

services:
  php:
    build: ./docker/php/
    ports:
      - "8080:80"
    environment:
      PHP_MYSQL_DBNAME: phpschool
      PHP_MYSQL_HOSTNAME: db
      PHP_MYSQL_PORT: 3306
      PHP_MYSQL_USER: root
      PHP_MYSQL_PASSWORD: toor
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  db:
    cap_add:
      - SYS_NICE
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./src/H06/phpschool.sql:/docker-entrypoint-initdb.d/phpschool.sql
      - mydb:/var/lib/mysql

volumes:
  mydb: