version: '3'

services:
  php:
    build: ./docker/php/
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  db:
    cap_add:
      - SYS_NICE
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb: